# Paths
workingDirectory: C:\Users\Thomas\Documents\dev\projects\ml\CVSP2019-Project-01a-Shot-Type-Classification-dl-based

model: Common\Models\model.h5
modelWeights: Common\Models\model_checkpoint_weights.h5

logs: Develop\Logs

trainFrames: C:\Users\Thomas\Pictures\db_v6\train
valFrames: C:\Users\Thomas\Pictures\db_v6\val
testFrames: C:\Users\Thomas\Pictures\db_v6\test

trainingEpochs: 10
targetImageSize: 224
