# Paths
model: C:/Users/Thomas/Documents/home/shottype/model/model.h5
modelWeights: C:/Users/Thomas/Documents/home/shottype/model/model_checkpoint_weights.h5

logs: C:/Users/Thomas/Documents/home/shottype/log

trainFrames: C:/Users/Thomas/Pictures/db_v6/train
valFrames: C:/Users/Thomas/Pictures/db_v6/val
testFrames: C:/Users/Thomas/Pictures/db_v6/test

# Training configuration
trainingEpochs: 10
targetImageSize: 224
useLRFinder: False
